import { AuthProvider } from "@/Contexts/AuthContext.jsx";
import "./globals.css";

export const metadata = {
  title: "Linktree",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
